apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: ennolerebulan/catalog-service:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: PORT
          value: "5001"
        - name: MONGO_URI
          value: "mongodb://admin:password123@mongodb-service:27017/hotelDB?authSource=admin"