apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: ennolerebulan/user-service:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: JWT_SECRET
          value: "supersecretkey"
        - name: MONGO_URI
          value: "mongodb://admin:password123@mongodb-service:27017/hotelDB?authSource=admin"